"""Tiny LaTeX table-fragment writer.

Each call writes a self-contained `\\begin{tabular}...\\end{tabular}` block to
disk, with consistent booktabs styling and an auto-generated header comment.
The fragment is intended to be `\\input{}` from the writeup, with the
caller's tex file owning `\\begin{table}` / `\\caption` / `\\label`.

Usage:
    write_tex_tabular(
        out_path=Path("tables/wall_clock.tex"),
        columns=["Method", "Train (s)", "Sample (s)", "Total (s)"],
        rows=[
            ["NPE-PFN", "0", "371 ± 13", "374 ± 13"],
            ["PFN-NPE (NSF)", "91 ± 41", "0", "95 ± 41"],
        ],
        column_align="lrrr",
        source_script="scripts/wall_clock_table.py",
    )

The caller is responsible for escaping (or pre-formatting) values; this
helper only assembles the tabular skeleton.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable


def _row_to_line(cells: Iterable[str]) -> str:
    return "  " + " & ".join(str(c) for c in cells) + r" \\"


def write_tex_tabular(
    *,
    out_path: Path,
    columns: list[str],
    rows: list[list[str]],
    column_align: str | None = None,
    midrules_after: list[int] | None = None,
    source_script: str | None = None,
) -> None:
    """Write a `\\begin{tabular}` fragment to `out_path`.

    Args:
        out_path: where to write. Parent directory is created if missing.
        columns: header row.
        rows: data rows. Each row's length must equal len(columns).
        column_align: e.g. "lrrr". Defaults to first column "l", remaining "r".
        midrules_after: list of 0-indexed row positions; a `\\midrule` is
            inserted *after* each listed row (useful for grouping).
        source_script: optional path to the script that wrote this fragment
            (recorded in the header comment so reviewers can trace provenance).
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if column_align is None:
        column_align = "l" + "r" * (len(columns) - 1)
    if len(column_align) != len(columns):
        raise ValueError(
            f"column_align length {len(column_align)} != n_columns {len(columns)}"
        )
    for i, r in enumerate(rows):
        if len(r) != len(columns):
            raise ValueError(
                f"row {i} has {len(r)} cells; expected {len(columns)}"
            )
    midset = set(midrules_after or [])

    lines: list[str] = []
    if source_script:
        lines.append(
            f"% Auto-generated by {source_script}. Do not edit by hand."
        )
    else:
        lines.append("% Auto-generated. Do not edit by hand.")
    lines.append(rf"\begin{{tabular}}{{{column_align}}}")
    lines.append(r"  \toprule")
    lines.append(_row_to_line(columns))
    lines.append(r"  \midrule")
    for i, r in enumerate(rows):
        lines.append(_row_to_line(r))
        if i in midset and i != len(rows) - 1:
            lines.append(r"  \midrule")
    lines.append(r"  \bottomrule")
    lines.append(r"\end{tabular}")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")
